# Generated by Django 4.2.2 on 2023-06-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Social',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('soci', models.CharField(max_length=200, verbose_name='Компания')),
                ('text', models.CharField(blank=True, max_length=200, verbose_name='Компания')),
                ('css_field', models.CharField(max_length=200, verbose_name='Компания')),
                ('link', models.URLField(verbose_name='Ссылка')),
            ],
            options={
                'verbose_name': 'Соц. сеть',
                'verbose_name_plural': 'оц. сети',
                'ordering': ('soci', 'text'),
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('company', models.CharField(default='AIWIKS', max_length=200, verbose_name='Компания')),
                ('telephone_1', models.CharField(default='+998 12 345-67-89', max_length=200, verbose_name='Телефон')),
                ('telephone_2', models.CharField(blank=True, default='+998 00 000-00-00', max_length=200, verbose_name='Телефон')),
                ('address', models.CharField(blank=True, max_length=200, verbose_name='Адрес')),
                ('social', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contacts.social', verbose_name='Соци')),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'ordering': ('company', 'address', 'telephone_1'),
            },
        ),
    ]
