# Generated by Django 4.2.2 on 2023-06-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='social',
            options={'ordering': ('soci', 'text'), 'verbose_name': 'Соц. сеть', 'verbose_name_plural': 'Соц. сети'},
        ),
        migrations.RemoveField(
            model_name='contact',
            name='social',
        ),
        migrations.AlterField(
            model_name='social',
            name='css_field',
            field=models.CharField(blank=True, max_length=200, verbose_name='Поля для css'),
        ),
        migrations.AlterField(
            model_name='social',
            name='link',
            field=models.URLField(blank=True, verbose_name='Ссылка'),
        ),
        migrations.AlterField(
            model_name='social',
            name='soci',
            field=models.CharField(max_length=200, verbose_name='Сеть'),
        ),
        migrations.AlterField(
            model_name='social',
            name='text',
            field=models.CharField(blank=True, max_length=200, verbose_name='Текст'),
        ),
        migrations.AddField(
            model_name='contact',
            name='social',
            field=models.ManyToManyField(to='contacts.social', verbose_name='Соци'),
        ),
    ]
