# Generated by Django 4.2.2 on 2023-06-21 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0003_contact_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='contact',
            name='about',
            field=models.TextField(default='asda', verbose_name='Соци'),
        ),
    ]
