# Generated by Django 4.2.2 on 2023-06-21 10:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0004_contact_about'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contact',
            name='about',
            field=models.TextField(verbose_name='Соци'),
        ),
    ]
