# Generated by Django 4.2.2 on 2023-06-24 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0005_alter_contact_about'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactPageForm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=150, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=150, verbose_name='Фамилия')),
                ('email', models.EmailField(max_length=254, verbose_name='e-mail')),
                ('phone', models.CharField(max_length=14, verbose_name='Телефон')),
                ('subject', models.CharField(max_length=100, verbose_name='Тема')),
                ('message', models.TextField(verbose_name='Текст сообщения')),
            ],
            options={
                'verbose_name': 'Сообщение',
                'verbose_name_plural': 'Сообщения',
            },
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('que', models.CharField(max_length=200, verbose_name='Вопрос 1')),
                ('ans', models.CharField(max_length=200, verbose_name='Ответ 1')),
            ],
            options={
                'verbose_name': 'ВопросОтвет',
                'verbose_name_plural': 'ВопросОтветы',
            },
        ),
    ]
