# Generated by Django 4.2.2 on 2023-06-25 17:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('contacts', '0006_contactpageform_faq'),
    ]

    operations = [
        migrations.AlterField(
            model_name='faq',
            name='ans',
            field=models.CharField(max_length=200, verbose_name='Ответ'),
        ),
        migrations.AlterField(
            model_name='faq',
            name='que',
            field=models.CharField(max_length=200, verbose_name='Вопрос'),
        ),
    ]
