# Generated by Django 4.2.2 on 2023-06-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=100, unique=True, verbose_name='Юзернейм')),
                ('image', models.ImageField(default='users/user_photo.png', upload_to=None, verbose_name='Изображение')),
                ('nickname', models.CharField(max_length=100, verbose_name='Никнейм')),
                ('gmail', models.EmailField(max_length=254, verbose_name='Имейл')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
                'ordering': ('nickname', 'gmail', 'user'),
            },
        ),
    ]
