# Generated by Django 4.2.2 on 2023-06-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(default='users/user_photo.png', upload_to='users/user_photo.png', verbose_name='Изображение'),
        ),
    ]
