# Generated by Django 4.2.2 on 2023-06-27 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_users_email'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('nickname', 'email', 'user'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='gmail',
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(max_length=254, verbose_name='Имейл'),
        ),
    ]
