# Generated by Django 4.2.2 on 2023-07-08 11:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0038_alter_movie_image_alter_movie_video_file'),
        ('users', '0005_alter_users_options_remove_users_gmail_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='password_1',
            field=models.CharField(default=123, max_length=100, verbose_name='Пароль'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='password_2',
            field=models.CharField(default=123, max_length=100, verbose_name='Подтверждение'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='users',
            name='user_movies',
            field=models.ForeignKey(default=123, on_delete=django.db.models.deletion.CASCADE, to='movies.movie', verbose_name='Фильмы пользователя'),
            preserve_default=False,
        ),
    ]
