# Generated by Django 4.2.2 on 2023-07-09 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_users_user_movies'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='premium',
            field=models.BooleanField(default=False),
        ),
    ]
