# Generated by Django 4.2.2 on 2023-07-09 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_users_premium'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='users/user_photo.png', upload_to='users/user_photo.png', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='users',
            name='user',
            field=models.CharField(max_length=100, verbose_name='Юзернейм'),
        ),
    ]
