# Generated by Django 4.2.2 on 2023-07-09 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0004_alter_music_files_alter_music_image_and_more'),
        ('movies', '0051_alter_genre_slug_alter_movie_genre'),
        ('users', '0009_alter_users_image_alter_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='user_movies',
            field=models.ManyToManyField(blank=True, to='movies.movie', verbose_name='Фильмы пользователя'),
        ),
        migrations.AddField(
            model_name='users',
            name='user_music',
            field=models.ManyToManyField(blank=True, to='music.music', verbose_name='Музыки пользователя'),
        ),
    ]
