# Generated by Django 4.2.2 on 2023-07-10 20:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_alter_users_managers_remove_users_date_joined_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='password_1',
        ),
        migrations.RemoveField(
            model_name='users',
            name='password_2',
        ),
    ]
