# Generated by Django 4.2.2 on 2023-07-10 22:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0013_remove_users_password_1_remove_users_password_2'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='users',
            options={'ordering': ('nickname', 'email'), 'verbose_name': 'Пользователь', 'verbose_name_plural': 'Пользователи'},
        ),
        migrations.RemoveField(
            model_name='users',
            name='user',
        ),
    ]
