# Generated by Django 4.2.2 on 2023-07-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0015_users_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='premium_expiry_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
