# Generated by Django 4.2.2 on 2023-07-12 12:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0052_userrating'),
        ('users', '0017_alter_users_premium_expiry_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_movies',
        ),
        migrations.CreateModel(
            name='UserSaved',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dropped_movies', models.ManyToManyField(blank=True, related_name='dropped_by_users', to='movies.movie')),
                ('favorite_movies', models.ManyToManyField(blank=True, related_name='favorited_by_users', to='movies.movie')),
                ('saved_movies', models.ManyToManyField(blank=True, related_name='saved_by_users', to='movies.movie')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
                ('watched_movies', models.ManyToManyField(blank=True, related_name='watched_by_users', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Фильм пользователя',
                'verbose_name_plural': 'Фильмы пользователя',
                'ordering': ('user',),
            },
        ),
        migrations.AddField(
            model_name='users',
            name='user_movies',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='users.usersaved', verbose_name='Фильмы пользователя'),
            preserve_default=False,
        ),
    ]
