# Generated by Django 4.2.2 on 2023-07-12 12:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0018_remove_users_user_movies_usersaved_users_user_movies'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='user_movies',
        ),
        migrations.RemoveField(
            model_name='users',
            name='user_music',
        ),
    ]
