# Generated by Django 4.2.2 on 2023-07-12 12:18

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0019_remove_users_user_movies_remove_users_user_music'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersaved',
            options={'verbose_name': 'Фильм пользователя', 'verbose_name_plural': 'Фильмы пользователя'},
        ),
        migrations.RemoveField(
            model_name='usersaved',
            name='user',
        ),
    ]
