# Generated by Django 4.2.2 on 2023-07-12 12:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0020_alter_usersaved_options_remove_usersaved_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='usersaved',
            options={'ordering': ('user',), 'verbose_name': 'Фильм пользователя', 'verbose_name_plural': 'Фильмы пользователя'},
        ),
        migrations.AddField(
            model_name='usersaved',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users'),
        ),
    ]
