# Generated by Django 4.2.2 on 2023-07-12 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0053_delete_userrating'),
        ('users', '0023_alter_usersavedmovies_dropped_movies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usersavedmovies',
            name='dropped_movies',
            field=models.ManyToManyField(blank=True, related_name='dropped_by_user', to='movies.movie', verbose_name='Эти фильмы вы бросили'),
        ),
        migrations.AlterField(
            model_name='usersavedmovies',
            name='favorite_movies',
            field=models.ManyToManyField(blank=True, related_name='favorited_by_user', to='movies.movie', verbose_name='Ваши любимые фильмы'),
        ),
        migrations.AlterField(
            model_name='usersavedmovies',
            name='saved_movies',
            field=models.ManyToManyField(blank=True, related_name='saved_by_user', to='movies.movie', verbose_name='Вы хотели посмотреть потом'),
        ),
        migrations.AlterField(
            model_name='usersavedmovies',
            name='watched_movies',
            field=models.ManyToManyField(blank=True, related_name='watched_by_user', to='movies.movie', verbose_name='Эти фильмы вы уже смотрели'),
        ),
    ]
