# Generated by Django 4.2.2 on 2023-07-12 22:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0008_alter_question_active'),
        ('users', '0024_alter_usersavedmovies_dropped_movies_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserAskedQnA',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ur_ans', models.ManyToManyField(blank=True, related_name='saved_by_user', to='QandA.answer', verbose_name='Вы хотели посмотреть потом')),
                ('ur_ques', models.ManyToManyField(blank=True, related_name='saved_by_user', to='QandA.question', verbose_name='Вы хотели посмотреть потом')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'Фильм пользователя',
                'verbose_name_plural': 'Фильмы пользователя',
                'ordering': ('user',),
            },
        ),
    ]
