# Generated by Django 4.2.2 on 2023-07-12 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0025_useraskedqna'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='useraskedqna',
            options={'ordering': ('user',), 'verbose_name': 'Вопрос и Ответ', 'verbose_name_plural': 'Вопрос и Ответ'},
        ),
    ]
