# Generated by Django 4.2.3 on 2023-07-19 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraskedqna_ur_ans_alter_useraskedqna_ur_ques'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='rating',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
