# Generated by Django 4.2.3 on 2023-07-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0028_users_rating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='users',
            name='rating',
            field=models.IntegerField(blank=True, default=False),
        ),
    ]
