# Generated by Django 4.2.3 on 2023-07-21 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0029_alter_users_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_confirmed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='users',
            name='image',
            field=models.ImageField(blank=True, default='users/user_photo.png', upload_to='users/user_photo', verbose_name='Изображение'),
        ),
    ]
