# Generated by Django 4.2.3 on 2023-07-22 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0031_alter_users_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='users',
            name='email_confirmation_code',
            field=models.CharField(blank=True, max_length=6),
        ),
    ]
