# Generated by Django 4.2.3 on 2023-07-23 15:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0014_answer_voters'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('users', '0032_users_email_confirmation_code'),
    ]

    operations = [
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_read', models.BooleanField(default=False)),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.answer')),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='QandA.question')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Уведомление',
                'verbose_name_plural': 'Уведомления',
                'ordering': ('user',),
            },
        ),
    ]
