# Generated by Django 4.2.2 on 2023-06-19 21:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Music',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Наименование')),
                ('author', models.CharField(max_length=100, verbose_name='Певец')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата выпуска')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('content', models.TextField(verbose_name='Тема')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('active', models.BooleanField(verbose_name='Показать')),
                ('image', models.ImageField(upload_to='QandA/images/', verbose_name='Изображение')),
                ('files', models.FileField(upload_to='QandA/files/', verbose_name='Файл')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости',
                'ordering': ('title', 'author', 'content'),
            },
        ),
    ]
