# Generated by Django 4.2.2 on 2023-06-25 22:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Видеофайл')),
                ('birth_date', models.DateField(blank=True, null=True, verbose_name='Видеофайл')),
                ('bio', models.TextField(blank=True, verbose_name='Видеофайл')),
                ('group', models.CharField(blank=True, max_length=100, verbose_name='Видеофайл')),
            ],
            options={
                'verbose_name': 'Для глав. страницы',
                'verbose_name_plural': 'Для глав. страницы',
            },
        ),
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Жанр')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Жанр',
                'verbose_name_plural': 'Жанры',
                'ordering': ['genre'],
            },
        ),
        migrations.CreateModel(
            name='ToShowMainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('short_description', models.CharField(max_length=200, verbose_name='Короткое описание')),
                ('video', models.FileField(blank=True, upload_to='movies/videos/main', verbose_name='Видеофайл')),
                ('popular', models.BooleanField(verbose_name='Что смотрят')),
                ('image', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='music.music', verbose_name='Фото')),
                ('slug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music.music')),
                ('title', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='name', to='music.music', verbose_name='Название')),
            ],
            options={
                'verbose_name': 'Для глав. страницы',
                'verbose_name_plural': 'Для глав. страницы',
            },
        ),
        migrations.AddField(
            model_name='music',
            name='genre',
            field=models.ManyToManyField(to='music.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='music',
            name='author',
            field=models.ForeignKey(max_length=100, on_delete=django.db.models.deletion.CASCADE, to='music.author', verbose_name='Певец'),
        ),
    ]
