# Generated by Django 4.2.2 on 2023-06-26 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0002_author_genre_toshowmainpage_music_genre_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='author',
            options={'verbose_name': 'Испольнитель', 'verbose_name_plural': 'Испольнители'},
        ),
        migrations.AlterModelOptions(
            name='music',
            options={'ordering': ('title', 'author', 'content'), 'verbose_name': 'Музыка', 'verbose_name_plural': 'Музыки'},
        ),
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(default=1, upload_to='music/author/', verbose_name='Изображение'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='author',
            name='bio',
            field=models.TextField(blank=True, verbose_name='Биография'),
        ),
        migrations.AlterField(
            model_name='author',
            name='birth_date',
            field=models.DateField(blank=True, null=True, verbose_name='Дата рождения'),
        ),
        migrations.AlterField(
            model_name='author',
            name='group',
            field=models.CharField(blank=True, max_length=100, verbose_name='Группа'),
        ),
        migrations.AlterField(
            model_name='author',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Испольнитель'),
        ),
        migrations.AlterField(
            model_name='music',
            name='files',
            field=models.FileField(blank=True, upload_to='QandA/files/', verbose_name='Файл'),
        ),
    ]
