# Generated by Django 4.2.2 on 2023-06-26 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0003_alter_author_options_alter_music_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='music',
            name='files',
            field=models.FileField(blank=True, upload_to='music/music/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='music',
            name='image',
            field=models.ImageField(upload_to='music/album/', verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='toshowmainpage',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткое описание'),
        ),
    ]
