# Generated by Django 4.2.1 on 2023-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articles', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='news',
            name='active',
            field=models.BooleanField(default=1, verbose_name='Показать'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default=False, max_length=100, verbose_name='Заголовок'),
        ),
    ]
