# Generated by Django 4.2.3 on 2023-07-15 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Banner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slide_1', models.ImageField(upload_to='photo_for_templates/', verbose_name='Фильмы')),
                ('slide_2', models.ImageField(upload_to='photo_for_templates/', verbose_name='Музыка')),
                ('slide_3', models.ImageField(upload_to='photo_for_templates/', verbose_name='В_О')),
            ],
            options={
                'verbose_name': 'Фото для страницы',
                'verbose_name_plural': 'Фото для страницы',
            },
        ),
    ]
