# Generated by Django 4.2.3 on 2023-07-17 11:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainpage', '0002_banner'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='banner',
            options={'verbose_name': 'Фото для баннера', 'verbose_name_plural': 'Фото для баннера'},
        ),
    ]
