# Generated by Django 4.2.2 on 2023-06-20 21:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Subs',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subscription_1', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Подписка на 1 месяц')),
                ('subscription_2', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Подписка на 3 месяц')),
                ('subscription_3', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Подписка на 6 месяц')),
                ('subscription_4', models.DecimalField(blank=True, decimal_places=2, max_digits=10, verbose_name='Подписка на 12 месяц')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Подписка',
                'verbose_name_plural': 'Подписки',
                'ordering': ('subscription_1', 'subscription_2', 'subscription_3', 'subscription_4'),
            },
        ),
        migrations.CreateModel(
            name='Subs_priv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
