# Generated by Django 4.2.2 on 2023-06-19 21:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Вопрос')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('content', models.TextField(verbose_name='Тема')),
                ('slug', models.SlugField(blank=True, unique=True)),
                ('active', models.BooleanField(verbose_name='Показать')),
                ('image', models.ImageField(upload_to='QandA/images/', verbose_name='Изображжение')),
                ('files', models.FileField(upload_to='QandA/files/', verbose_name='Файл')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.users')),
            ],
            options={
                'verbose_name': 'Вопрос',
                'verbose_name_plural': 'Вопроы',
                'ordering': ('title', 'author', 'content'),
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Комментарий')),
                ('active', models.BooleanField(verbose_name='Показать')),
                ('image', models.ImageField(upload_to='QandA/images/', verbose_name='Изображжение')),
                ('files', models.FileField(upload_to='QandA/files/', verbose_name='Файл')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanda_comments', to='users.users')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='QandA.question')),
            ],
            options={
                'verbose_name': 'Коммент',
                'verbose_name_plural': 'Комментарии',
                'ordering': ('topic', 'commentator', 'content'),
            },
        ),
    ]
