# Generated by Django 4.2.2 on 2023-06-26 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0002_rename_comment_answer'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(max_length=50, verbose_name='Теги')),
                ('slug', models.SlugField(blank=True, unique=True)),
            ],
            options={
                'verbose_name': 'Тег',
                'verbose_name_plural': 'Теги',
                'ordering': ['genre'],
            },
        ),
        migrations.AddField(
            model_name='question',
            name='genre',
            field=models.ManyToManyField(to='QandA.tag', verbose_name='тег'),
        ),
    ]
