# Generated by Django 4.2.2 on 2023-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0003_tag_question_genre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='content',
            field=models.TextField(verbose_name='Содержанеие'),
        ),
        migrations.AlterField(
            model_name='question',
            name='files',
            field=models.FileField(blank=True, upload_to='QandA/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='question',
            name='image',
            field=models.ImageField(blank=True, upload_to='QandA/images/', verbose_name='Изображжение'),
        ),
    ]
