# Generated by Django 4.2.2 on 2023-06-27 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0004_alter_question_content_alter_question_files_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='slug',
        ),
    ]
