# Generated by Django 4.2.2 on 2023-06-27 13:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0005_remove_question_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='files',
            field=models.FileField(blank=True, upload_to='QandA/files/', verbose_name='Файл'),
        ),
        migrations.AlterField(
            model_name='answer',
            name='image',
            field=models.ImageField(blank=True, upload_to='QandA/images/', verbose_name='Изображжение'),
        ),
    ]
