# Generated by Django 4.2.2 on 2023-06-27 13:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0006_alter_answer_files_alter_answer_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
    ]
