# Generated by Django 4.2.2 on 2023-07-12 22:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0007_alter_answer_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='question',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Показать'),
        ),
    ]
