# Generated by Django 4.2.2 on 2023-07-12 23:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraskedqna_ur_ans_alter_useraskedqna_ur_ques'),
        ('QandA', '0008_alter_question_active'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('topic', 'content'), 'verbose_name': 'Коммент', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='commentator',
        ),
        migrations.AddField(
            model_name='answer',
            name='commentator',
            field=models.ManyToManyField(related_name='qanda_comments', to='users.users'),
        ),
    ]
