# Generated by Django 4.2.2 on 2023-07-13 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0009_alter_answer_options_remove_answer_commentator_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='answer',
            options={'ordering': ('content',), 'verbose_name': 'Коммент', 'verbose_name_plural': 'Комментарии'},
        ),
        migrations.RemoveField(
            model_name='answer',
            name='topic',
        ),
        migrations.AddField(
            model_name='answer',
            name='topic',
            field=models.ManyToManyField(related_name='comments', to='QandA.question'),
        ),
    ]
