# Generated by Django 4.2.3 on 2023-07-18 21:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0027_alter_useraskedqna_ur_ans_alter_useraskedqna_ur_ques'),
        ('QandA', '0010_alter_answer_options_remove_answer_topic_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reply',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('content', models.TextField(verbose_name='Ответ')),
                ('active', models.BooleanField(default=True, verbose_name='Показать')),
                ('image', models.ImageField(blank=True, upload_to='QandA/images/', verbose_name='Изображжение')),
                ('files', models.FileField(blank=True, upload_to='QandA/files/', verbose_name='Файл')),
                ('answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='replies', to='QandA.answer')),
                ('commentator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='qanda_replies', to='users.users')),
            ],
            options={
                'verbose_name': 'Ответ',
                'verbose_name_plural': 'Ответы',
                'ordering': ('created_at',),
            },
        ),
    ]
