# Generated by Django 4.2.3 on 2023-07-19 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0011_reply'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Reply',
        ),
    ]
