# Generated by Django 4.2.3 on 2023-07-19 13:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QandA', '0013_answer_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='answer',
            name='voters',
            field=models.JSONField(default=dict),
        ),
    ]
