# Generated by Django 4.2.1 on 2023-06-02 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Жанр')),
            ],
        ),
        migrations.CreateModel(
            name='Movie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField(verbose_name='Наименование')),
                ('director', models.TextField(verbose_name='Режиссер')),
                ('rating', models.IntegerField(verbose_name='Рейтинг')),
                ('budget', models.IntegerField(verbose_name='Бюджет')),
                ('release_date', models.DateField()),
                ('on_screens', models.BooleanField(default=False)),
                ('genre', models.ManyToManyField(to='movies.genre')),
            ],
            options={
                'verbose_name': 'Фильм',
                'verbose_name_plural': 'Фильмы',
            },
        ),
    ]
