# Generated by Django 4.2.1 on 2023-06-02 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='image',
            field=models.ImageField(default=1, upload_to='', verbose_name='Постер'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(max_length=100, verbose_name='Режиссер'),
        ),
    ]
