# Generated by Django 4.2.1 on 2023-06-02 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0005_alter_movie_options_movie_video_file_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, upload_to='media/movies/videos', verbose_name='Видеофайл'),
        ),
    ]
