# Generated by Django 4.2.1 on 2023-06-02 20:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0007_alter_genre_options_alter_movie_image_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(to='movies.genre', verbose_name='Жанры'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='on_screens',
            field=models.BooleanField(default=False, verbose_name='На экранах '),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, max_digits=5, verbose_name='Рейтинг'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='release_date',
            field=models.DateField(verbose_name='Дата релиза'),
        ),
    ]
