# Generated by Django 4.2.1 on 2023-06-02 20:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0008_alter_movie_genre_alter_movie_on_screens_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='budget',
            field=models.IntegerField(default=False, verbose_name='Бюджет'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='director',
            field=models.CharField(default=False, max_length=100, verbose_name='Режиссер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=False, max_digits=5, verbose_name='Рейтинг'),
        ),
    ]
