# Generated by Django 4.2.1 on 2023-06-18 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0009_alter_movie_budget_alter_movie_director_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='active',
            field=models.BooleanField(blank=True, default=False, verbose_name='Показать'),
        ),
    ]
