# Generated by Django 4.2.1 on 2023-06-18 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0010_movie_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
