# Generated by Django 4.2.1 on 2023-06-18 19:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0011_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='slug',
        ),
    ]
