# Generated by Django 4.2.1 on 2023-06-18 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0012_remove_movie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='movie',
            name='slug',
            field=models.SlugField(default=1),
            preserve_default=False,
        ),
    ]
