# Generated by Django 4.2.2 on 2023-06-22 12:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0017_alter_movie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='ToShowMainpage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ManyToManyField(related_name='images', to='movies.movie')),
                ('short_description', models.ManyToManyField(related_name='short_description', to='movies.movie')),
                ('title', models.ManyToManyField(related_name='title', to='movies.movie')),
                ('video', models.ManyToManyField(related_name='video', to='movies.movie')),
            ],
            options={
                'verbose_name': 'Для глав. страницы',
                'verbose_name_plural': 'Для глав. страницы',
            },
        ),
    ]
