# Generated by Django 4.2.2 on 2023-06-22 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0018_toshowmainpage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toshowmainpage',
            name='image',
            field=models.ManyToManyField(max_length=100, related_name='images', to='movies.movie', verbose_name='Фото'),
        ),
        migrations.RemoveField(
            model_name='toshowmainpage',
            name='short_description',
        ),
        migrations.AlterField(
            model_name='toshowmainpage',
            name='title',
            field=models.ManyToManyField(related_name='title', to='movies.movie', verbose_name='Название'),
        ),
        migrations.RemoveField(
            model_name='toshowmainpage',
            name='video',
        ),
        migrations.AddField(
            model_name='toshowmainpage',
            name='short_description',
            field=models.CharField(default=1, max_length=100, verbose_name='Короткое описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toshowmainpage',
            name='video',
            field=models.FileField(default=1, upload_to='', verbose_name='Видеофайл'),
            preserve_default=False,
        ),
    ]
