# Generated by Django 4.2.2 on 2023-06-22 14:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0019_alter_toshowmainpage_image_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='toshowmainpage',
            name='image',
        ),
        migrations.RemoveField(
            model_name='toshowmainpage',
            name='title',
        ),
        migrations.AddField(
            model_name='toshowmainpage',
            name='image',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='movies.movie', verbose_name='Фото'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='toshowmainpage',
            name='title',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='title', to='movies.movie', verbose_name='Название'),
            preserve_default=False,
        ),
    ]
