# Generated by Django 4.2.2 on 2023-06-22 15:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0021_alter_toshowmainpage_short_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toshowmainpage',
            name='video',
            field=models.FileField(upload_to='movies/videos/main', verbose_name='Видеофайл'),
        ),
    ]
