# Generated by Django 4.2.2 on 2023-06-22 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0022_alter_toshowmainpage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='toshowmainpage',
            name='popular',
            field=models.BooleanField(default=1, verbose_name='Что смотрят'),
            preserve_default=False,
        ),
    ]
