# Generated by Django 4.2.2 on 2023-06-22 19:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0023_toshowmainpage_popular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toshowmainpage',
            name='video',
            field=models.FileField(blank=True, upload_to='movies/videos/main', verbose_name='Видеофайл'),
        ),
    ]
