# Generated by Django 4.2.2 on 2023-06-23 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0024_alter_toshowmainpage_video'),
    ]

    operations = [
        migrations.AddField(
            model_name='toshowmainpage',
            name='slug',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='movies.movie'),
            preserve_default=False,
        ),
    ]
