# Generated by Django 4.2.2 on 2023-06-23 18:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0031_alter_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
