# Generated by Django 4.2.2 on 2023-06-24 19:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0032_alter_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
