# Generated by Django 4.2.2 on 2023-06-25 22:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0035_remove_genre_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, unique=True),
        ),
    ]
