# Generated by Django 4.2.2 on 2023-06-25 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0036_genre_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genre',
            name='slug',
        ),
    ]
