# Generated by Django 4.2.2 on 2023-06-27 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0037_remove_genre_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='movie',
            name='image',
            field=models.ImageField(upload_to='static/posters', verbose_name='Постер'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='video_file',
            field=models.FileField(blank=True, upload_to='static/videos', verbose_name='Видеофайл'),
        ),
    ]
