# Generated by Django 4.2.2 on 2023-07-08 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0046_alter_genre_slug_alter_movie_slug'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='movie',
            name='genre',
        ),
        migrations.AddField(
            model_name='movie',
            name='genre',
            field=models.CharField(default=123, max_length=100, verbose_name='Наименование'),
            preserve_default=False,
        ),
    ]
