# Generated by Django 4.2.2 on 2023-07-08 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0048_alter_genre_slug_remove_movie_genre_alter_movie_slug_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, default=''),
        ),
        migrations.AlterField(
            model_name='movie',
            name='slug',
            field=models.SlugField(blank=True),
        ),
    ]
