# Generated by Django 4.2.2 on 2023-07-08 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0049_alter_genre_slug_alter_movie_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genre',
            name='slug',
            field=models.SlugField(blank=True, default='asd'),
        ),
        migrations.AlterField(
            model_name='movie',
            name='genre',
            field=models.ManyToManyField(default='asd', to='movies.genre', verbose_name='Жанры'),
        ),
    ]
