# Generated by Django 4.2.2 on 2023-07-12 16:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0052_userrating'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserRating',
        ),
    ]
