# Generated by Django 4.2.3 on 2023-07-17 11:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('movies', '0053_delete_userrating'),
    ]

    operations = [
        migrations.AlterField(
            model_name='toshowmainpage',
            name='short_description',
            field=models.CharField(blank=True, max_length=200, verbose_name='Короткое описание'),
        ),
    ]
